# Generated by Django 4.1.7 on 2023-03-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('firebase_id', models.CharField(max_length=100)),
                ('dexcom_id', models.CharField(max_length=100)),
            ],
        ),
    ]
