# Generated by Django 4.1.7 on 2023-03-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dex_app', '0002_user_dexcom_password_user_dexcom_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insulin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('dose', models.FloatField()),
                ('time', models.DateTimeField()),
                ('maker', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('short', 'Short-acting'), ('long', 'Long-acting')], max_length=5)),
            ],
        ),
    ]
