# Generated by Django 4.1.7 on 2023-03-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dex_app', '0004_remove_insulin_user_id_insulin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insulin',
            name='maker',
        ),
    ]
